FROM node:22-bookworm-slim AS build

WORKDIR /app
ARG VITE_AUTH_CSRF_COOKIE_NAME=moodlelike_csrf
ARG VITE_AUTH_CSRF_HEADER_NAME=X-CSRF-Token
ARG VITE_AGENT_WEB_ENABLED=true
ARG VITE_AGENT_PRACTICE_WRITE_ENABLED=true
ARG VITE_AGENT_DISABLED_REDIRECT_URL=/
ENV VITE_AUTH_CSRF_COOKIE_NAME=${VITE_AUTH_CSRF_COOKIE_NAME}
ENV VITE_AUTH_CSRF_HEADER_NAME=${VITE_AUTH_CSRF_HEADER_NAME}
ENV VITE_AGENT_WEB_ENABLED=${VITE_AGENT_WEB_ENABLED}
ENV VITE_AGENT_PRACTICE_WRITE_ENABLED=${VITE_AGENT_PRACTICE_WRITE_ENABLED}
ENV VITE_AGENT_DISABLED_REDIRECT_URL=${VITE_AGENT_DISABLED_REDIRECT_URL}
COPY package*.json ./
COPY frontend/package*.json ./frontend/
RUN npm ci && npm --prefix frontend ci

COPY frontend ./frontend
RUN npm --prefix frontend run build

FROM nginx:1.27-alpine

COPY deploy/nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=build /app/frontend/dist /usr/share/nginx/html

EXPOSE 80
