ALTER TABLE "schools" ADD COLUMN "version" INTEGER NOT NULL DEFAULT 1;
ALTER TABLE "school_programs" ADD COLUMN "version" INTEGER NOT NULL DEFAULT 1;
ALTER TABLE "school_csca_rules" ADD COLUMN "version" INTEGER NOT NULL DEFAULT 1;
ALTER TABLE "school_scholarships" ADD COLUMN "version" INTEGER NOT NULL DEFAULT 1;
ALTER TABLE "scholarships" ADD COLUMN "version" INTEGER NOT NULL DEFAULT 1;
