export const routes = {
  home: '/',
  cscaPrep: '/csca-prep',
  cscaExamTime: '/csca-exam-time',
  cscaSubjects: '/csca-subjects',
  cscaMockExam: '/csca-mock-exam',
  pastPapers: '/past-papers',
  consulting: '/services/consulting',
  aiCoachService: '/services/ai-coach',
  agent: '/agent',
  adminAudit: '/admin/audit',
  adminAiOperations: '/admin/ai',
  adminAIQuestionBank: '/admin/ai-question-bank',
  adminContent: '/admin/content',
  adminTeachingAssets: '/admin/content/teaching-assets',
  adminMockExams: '/admin/mock-exams',
  adminLearningMockExams: '/admin/learning/mock-exams',
  adminLearningPastPapers: '/admin/learning/past-papers',
  adminLearningSpecialPractice: '/admin/learning/special-practice',
  adminPastPapers: '/admin/past-papers',
  adminSpecialPractice: '/admin/special-practice',
  adminAccountsOrganizations: '/admin/accounts/organizations',
  adminAccountsUsers: '/admin/accounts/users',
  adminOrganizations: '/admin/organizations',
  adminUsers: '/admin/users',
  adminAuditLogs: '/admin/audit-logs',
  organization: '/organization',
  organizationInvite: '/organization/invite',
  auth: '/auth',
  login: '/login',
  register: '/register',
  onboarding: '/onboarding',
  me: '/me'
} as const;

export type PublicRoute = (typeof routes)[keyof typeof routes] | string;
